NerdIcons = {
    TUI = {
        Ellipsis = "…",
        CollapsedGroup = "",
        ExpandedGroup = "",
        LineContinuation = "↳",
        LineEnd = "⏎",
        VisibleSpace = "·",
        VisibleTab = "▶",
        MissingLine = "╱",
        IndentLevel = "│",
        PromptPrefix = '',
        SelectionPrefix = '',
    },
    Diagnostics = {
        Logo = "󰒡",
        Prefix = "●",
        LSP = {
            Error = " ",
            Warn = " ",
            Hint = " ",
            Info = " ",
        },
        DAP = {
            Stopped = "󰁕 ",
            Breakpoint = " ",
            BreakpointCondition = " ",
            BreakpointRejected = " ",
            LogPoint = ".>",
        },
    },
    cmp_categories = {
        Array = " ",
        Boolean = " ",
        Class = " ",
        Color = " ",
        Constant = " ",
        Constructor = " ",
        Copilot = " ",
        Enum = " ",
        EnumMember = " ",
        Event = " ",
        Field = " ",
        File = " ",
        Folder = " ",
        Function = " ",
        Interface = " ",
        Key = " ",
        Keyword = " ",
        Method = " ",
        Module = " ",
        Namespace = " ",
        Null = " ",
        Number = " ",
        Object = " ",
        Operator = " ",
        Package = " ",
        Property = " ",
        Reference = " ",
        Snippet = " ",
        String = " ",
        Struct = " ",
        Text = " ",
        TypeParameter = " ",
        Unit = " ",
        Value = " ",
        Variable = " ",
    },
    SourceSymbols = {
        Array = "󰅪",
        Boolean = "⊨",
        Class = "󰌗",
        Constructor = "",
        Key = "󰌆",
        Namespace = "󰅪",
        Null = "NULL",
        Number = "#",
        Object = "󰀚",
        Package = "󰏗",
        Property = "",
        Reference = "",
        Snippet = "",
        String = "󰀬",
        TypeParameter = "󰊄",
        Unit = "",
    },
    git = {
        Logo = "󰊢",
        Added = " ",
        Modified = " ",
        Removed = " ",
        Branch = "",
        Conflict = "",
        Ignored = "◌",
        Renamed = "➜",
        Staged = "✓",
        Unstaged = "✗",
        Untracked = "★",
        Signs = {
            Add = "▌",
            Change = "▌",
            Delete = "",
            TopDelete = "",
            ChangeDelete = "▌",
            Untracked = "▌" ,
        },
    },

    Dependencies = {
        Installed = "✓",
        Uninstalled = "✗",
        Pending = "⟳",
    },
    ui = {
        LSP = "",
        Debugger = "",
        File = "󰈙",
        Files = " ",
        Diagnostic = "󰒡",
        Git = "󰊢",
        UI = "󰏖",
        Help = "󰋖",
        Buffers = "󱂬",
        Search = "",
        Fix = "󰁨",
        Next = "󰼧",
        Prev = "󰒮",
        Jump = "󱔕",
        Files = " ",
        Sleep = "󰒲 ",
        Quit = " ",
        Explorer = " ",
        Dirty = "󰋮",
        Speed = "⚡",
        PromptPrefix = "",
        Clock = "",
        FolderClosed = "",
        FolderEmpty = "",
        FolderOpen = "",
        FileModified = "",
        Test = "󰙨"
    },
}


return NerdIcons
