return {
    'AstroNvim/astrocommunity',

    { import = 'astrocommunity.git.neogit' },
    { import = 'astrocommunity.git.diffview-nvim' },
    { import = 'astrocommunity.utility.noice-nvim' },
    { import = 'astrocommunity.colorscheme.catppuccin' },
    { import = 'astrocommunity.completion.copilot-lua-cmp' },
    { import = 'astrocommunity.scrolling.nvim-scrollbar' },
    { import = 'astrocommunity.debugging.nvim-dap-virtual-text' },
    { import = 'astrocommunity.pack.prisma' },
    { import = 'astrocommunity.pack.docker' },
    { import = 'astrocommunity.pack.go' },
    { import = 'astrocommunity.pack.html-css' },
    { import = 'astrocommunity.pack.json' },
    { import = 'astrocommunity.pack.lua' },
    { import = 'astrocommunity.pack.python' },
    { import = 'astrocommunity.pack.toml' },
    { import = 'astrocommunity.pack.typescript' },
    { import = 'astrocommunity.pack.yaml' },
    { import = 'astrocommunity.pack.bash' },
}
