std = {
    globals = { 'vim', '_G', '_' },
    read_globals = {
        'pcall',
        'pairs',
        'ipairs',
        'table',
        'error',
        'type',
        'string',
        'fatal',
        'dbg',
        'who',
        'assert',
        'require',
        'package',
        'unpack',
        'math',
        'os',
        'next',
        'debug',
        'tostring',
        'tonumber',
    },
}
